/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as AlbumRouteImport } from './routes/album'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectSlugRouteImport } from './routes/project.$slug'
import { Route as CertificateIdRouteImport } from './routes/certificate.$id'
import { Route as AdminToolsRouteImport } from './routes/admin.tools'
import { Route as AdminSignInRouteImport } from './routes/admin.sign-in'
import { Route as AdminGalelyRouteImport } from './routes/admin.galely'
import { Route as AdminExperienceRouteImport } from './routes/admin.experience'
import { Route as AdminBioRouteImport } from './routes/admin.bio'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumRoute = AlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugRoute = ProjectSlugRouteImport.update({
  id: '/project/$slug',
  path: '/project/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateIdRoute = CertificateIdRouteImport.update({
  id: '/certificate/$id',
  path: '/certificate/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminToolsRoute = AdminToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSignInRoute = AdminSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalelyRoute = AdminGalelyRouteImport.update({
  id: '/galely',
  path: '/galely',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExperienceRoute = AdminExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBioRoute = AdminBioRouteImport.update({
  id: '/bio',
  path: '/bio',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/album': typeof AlbumRoute
  '/certificates': typeof CertificatesRoute
  '/contact': typeof ContactRoute
  '/work': typeof WorkRoute
  '/admin/bio': typeof AdminBioRoute
  '/admin/experience': typeof AdminExperienceRoute
  '/admin/galely': typeof AdminGalelyRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/admin/tools': typeof AdminToolsRoute
  '/certificate/$id': typeof CertificateIdRoute
  '/project/$slug': typeof ProjectSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/album': typeof AlbumRoute
  '/certificates': typeof CertificatesRoute
  '/contact': typeof ContactRoute
  '/work': typeof WorkRoute
  '/admin/bio': typeof AdminBioRoute
  '/admin/experience': typeof AdminExperienceRoute
  '/admin/galely': typeof AdminGalelyRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/admin/tools': typeof AdminToolsRoute
  '/certificate/$id': typeof CertificateIdRoute
  '/project/$slug': typeof ProjectSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/album': typeof AlbumRoute
  '/certificates': typeof CertificatesRoute
  '/contact': typeof ContactRoute
  '/work': typeof WorkRoute
  '/admin/bio': typeof AdminBioRoute
  '/admin/experience': typeof AdminExperienceRoute
  '/admin/galely': typeof AdminGalelyRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/admin/tools': typeof AdminToolsRoute
  '/certificate/$id': typeof CertificateIdRoute
  '/project/$slug': typeof ProjectSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/album'
    | '/certificates'
    | '/contact'
    | '/work'
    | '/admin/bio'
    | '/admin/experience'
    | '/admin/galely'
    | '/admin/sign-in'
    | '/admin/tools'
    | '/certificate/$id'
    | '/project/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/album'
    | '/certificates'
    | '/contact'
    | '/work'
    | '/admin/bio'
    | '/admin/experience'
    | '/admin/galely'
    | '/admin/sign-in'
    | '/admin/tools'
    | '/certificate/$id'
    | '/project/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/album'
    | '/certificates'
    | '/contact'
    | '/work'
    | '/admin/bio'
    | '/admin/experience'
    | '/admin/galely'
    | '/admin/sign-in'
    | '/admin/tools'
    | '/certificate/$id'
    | '/project/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlbumRoute: typeof AlbumRoute
  CertificatesRoute: typeof CertificatesRoute
  ContactRoute: typeof ContactRoute
  WorkRoute: typeof WorkRoute
  CertificateIdRoute: typeof CertificateIdRoute
  ProjectSlugRoute: typeof ProjectSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album': {
      id: '/album'
      path: '/album'
      fullPath: '/album'
      preLoaderRoute: typeof AlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$slug': {
      id: '/project/$slug'
      path: '/project/$slug'
      fullPath: '/project/$slug'
      preLoaderRoute: typeof ProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/$id': {
      id: '/certificate/$id'
      path: '/certificate/$id'
      fullPath: '/certificate/$id'
      preLoaderRoute: typeof CertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tools': {
      id: '/admin/tools'
      path: '/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AdminToolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sign-in': {
      id: '/admin/sign-in'
      path: '/sign-in'
      fullPath: '/admin/sign-in'
      preLoaderRoute: typeof AdminSignInRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/galely': {
      id: '/admin/galely'
      path: '/galely'
      fullPath: '/admin/galely'
      preLoaderRoute: typeof AdminGalelyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/experience': {
      id: '/admin/experience'
      path: '/experience'
      fullPath: '/admin/experience'
      preLoaderRoute: typeof AdminExperienceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bio': {
      id: '/admin/bio'
      path: '/bio'
      fullPath: '/admin/bio'
      preLoaderRoute: typeof AdminBioRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBioRoute: typeof AdminBioRoute
  AdminExperienceRoute: typeof AdminExperienceRoute
  AdminGalelyRoute: typeof AdminGalelyRoute
  AdminSignInRoute: typeof AdminSignInRoute
  AdminToolsRoute: typeof AdminToolsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBioRoute: AdminBioRoute,
  AdminExperienceRoute: AdminExperienceRoute,
  AdminGalelyRoute: AdminGalelyRoute,
  AdminSignInRoute: AdminSignInRoute,
  AdminToolsRoute: AdminToolsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AlbumRoute: AlbumRoute,
  CertificatesRoute: CertificatesRoute,
  ContactRoute: ContactRoute,
  WorkRoute: WorkRoute,
  CertificateIdRoute: CertificateIdRoute,
  ProjectSlugRoute: ProjectSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
